//
// Created by kaina on 2024/7/21.
//

#ifndef AAUDIORECORDER_AAUDIO_RECORDER_H
#define AAUDIORECORDER_AAUDIO_RECORDER_H

#define ENABLE_CALLBACK 1
#define USE_WAV_HEADER 1
#define MAX_DATA_SIZE (1 * 1024 * 1024 * 1024)

#endif //AAUDIORECORDER_AAUDIO_RECORDER_H
